language: java
env:
  global:
before_install:
- openssl aes-256-cbc -K $encrypted_989c68ae90fa_key -iv $encrypted_989c68ae90fa_iv -in amazonkey-coronhackathon.pem.enc -out amazonkey-coronhackathon.pem -d
- cd back
- chmod +x gradlew
# whitelist
branches:
  only:
    - master
    - continuous-deployment
deploy:
  provider: script
  skip_cleanup: true
  script: bash ../deploy.sh 23.20.204.191
  on:
    branch: continuous-deployment
