language: java
cache:
  directories:
  - back/build
before_install:
- cd back
- chmod +x gradlew
# whitelist
branches:
  only:
    - master
    - continuous-deployment
deploy:
  provider: script
  skip_cleanup: true
  script: bash ../deploy.sh "ec2-18-234-142-249.compute-1.amazonaws.com"
  on:
    branch: continuous-deployment
